In [1]:
import pandas as pd
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.table import Table
from astroquery.mast import Catalogs

## Data loads

### Folder parsing

In [13]:
data_folder = '/Users/philvanlane/Documents/lc_ae/data/'
hosts_folder = '/Users/philvanlane/Documents/lc_ae/exop_hosts/'
targets = pd.read_csv(data_folder + 'Pass_Feinstein_TICs.csv')
hosts = pd.read_csv(hosts_folder + 'host_ids.csv')
moca_old = pd.read_csv(data_folder + 'mocadb_add_old_LCs.csv',dtype={'target_name': str})

### Get TICs for all other targets

In [9]:
target = targets.iloc[0]
res = Catalogs.query_criteria(catalog='Tic',ID=target.TIC_ID)

In [13]:
for i in range(len(targets)):
    if i % 500 == 0:
        print(f'Processing target {i+1}/{len(targets)}')
    target = targets.iloc[i]

    try:
        res = Catalogs.query_criteria(catalog='Tic',ID=target.TIC_ID)
        Gaia_ID = res[0]['GAIA']

    except Exception as e:
        Gaia_ID = 'N/A'

    targets.loc[i,'Gaia_ID'] = Gaia_ID

Processing target 1/6848
Processing target 501/6848
Processing target 1001/6848
Processing target 1501/6848
Processing target 2001/6848
Processing target 2501/6848
Processing target 3001/6848
Processing target 3501/6848
Processing target 4001/6848
Processing target 4501/6848
Processing target 5001/6848
Processing target 5501/6848
Processing target 6001/6848
Processing target 6501/6848

In [16]:
targets.to_csv(data_folder + 'Pass_Feinstein_TICs_with_DR2.csv', index=False)

In [104]:
targets_multi = targets.loc[targets['msg'] == '2 results']

In [109]:
targets_multi

,object,source_survey_name,source_survey_id,ref,TIC_ID,Gaia_ID,msg
30,2207738916728293888,gaia2,2207738916728293888,Kiman2021,435160829,2207738916728293888,2 results
58,2959966528395087104,gaia2,2959966528395087104,Kiman2021,146559015,2959966528395087104,2 results
75,2MASS J02141251-0357434,2MASS,J02141251-0357434,Pass2023,471012790,--,2 results
101,2MASS J05015746-0656459,2MASS,J05015746-0656459,LWRD,471012347,--,2 results
114,2MASS J07171706-0501031,2MASS,J07171706-0501031,Pass2023,51159255,3059246454092369024,2 results
200,2MASS J22230696-1736250,2MASS,J22230696-1736250,Pass2023,471012250,--,2 results
208,2MASS J23351050-0223214,2MASS,J23351050-0223214,LWRD,471016474,2640434056928150400,2 results
268,374400893423204992,gaia2,374400893423204992,Kiman2021,600573015,374400893423204992,2 results
304,4670526284404823808,gaia2,4670526284404823808,Kiman2021,31780319,4670526284404823808,2 results
330,4738546128148599296,gaia2,4738546128148599296,Kiman2021,201897406,4738546128148599296,2 results
414,5343603288120259072,gaia2,5343603288120259072,Kiman2021,375838965,5343603288120259072,2 results
437,5855801434094995584,gaia2,5855801434094995584,Kiman2021,329161967,5855801434094995584,2 results
561,6244148803549549312,gaia2,6244148803549549312,Kiman2021,1259769920,6244148803549549312,2 results
642,6388245295629220608,gaia2,6388245295629220608,Kiman2021,2054867096,6388245295629220608,2 results
802,661211147230556160,gaia2,661211147230556160,Kiman2021,175261870,661211147230556160,2 results
1143,J16553529-0823401,2MASS,J16553529-0823401,Pass2024,471012515,--,2 results

In [112]:
for i,r in targets_multi.iterrows():
    
    try:
        if r.source_survey_name == 'gaia2':
            res = Catalogs.query_criteria(catalog='Tic',GAIA=r.source_survey_id)
        elif r.source_survey_name == '2MASS':
            twomass_id = r.source_survey_id[1:]
            res = Catalogs.query_criteria(catalog='Tic',TWOMASS=twomass_id)
        elif r.source_survey_name == 'HIP':
            res = Catalogs.query_criteria(catalog='Tic',HIP=r.source_survey_id)
        elif r.source_survey_name == 'TYC':
            res = Catalogs.query_criteria(catalog='Tic',TYC=r.source_survey_id)
        elif r.source_survey_name == 'UCAC3':
            res = Catalogs.query_criteria(catalog='Tic',UCAC=r.source_survey_id)
        elif r.source_survey_name == 'UCAC4':
            res = Catalogs.query_criteria(catalog='Tic',UCAC=r.source_survey_id)
        
        for r_row in res:
            print(r.object,',',r.source_survey_name,',',r.source_survey_id,',',r.ref,',', r_row['ID'],',',r_row['GAIA'])
    except Exception as e:
        print("Error querying TIC")

2207738916728293888 , gaia2 , 2207738916728293888 , Kiman2021 , 435160829 , 2207738916728293888
2207738916728293888 , gaia2 , 2207738916728293888 , Kiman2021 , 2049313432 , 2207738916728293888
2959966528395087104 , gaia2 , 2959966528395087104 , Kiman2021 , 146559015 , 2959966528395087104
2959966528395087104 , gaia2 , 2959966528395087104 , Kiman2021 , 671115667 , 2959966528395087104
2MASS J02141251-0357434 , 2MASS , J02141251-0357434 , Pass2023 , 471012790 , --
2MASS J02141251-0357434 , 2MASS , J02141251-0357434 , Pass2023 , 332819239 , 2492866780297999232
2MASS J05015746-0656459 , 2MASS , J05015746-0656459 , LWRD , 471012347 , --
2MASS J05015746-0656459 , 2MASS , J05015746-0656459 , LWRD , 43605290 , 3187115498866675456
2MASS J07171706-0501031 , 2MASS , J07171706-0501031 , Pass2023 , 51159255 , 3059246454092369024
2MASS J07171706-0501031 , 2MASS , J07171706-0501031 , Pass2023 , 471012349 , --
2MASS J22230696-1736250 , 2MASS , J22230696-1736250 , Pass2023 , 471012250 , --
2MASS J22230696-1736250 , 2MASS , J22230696-1736250 , Pass2023 , 12652442 , 2595284016771502080
2MASS J23351050-0223214 , 2MASS , J23351050-0223214 , LWRD , 313884966 , --
2MASS J23351050-0223214 , 2MASS , J23351050-0223214 , LWRD , 471016474 , 2640434056928150400
374400893423204992 , gaia2 , 374400893423204992 , Kiman2021 , 471012662 , 374400893423204992
374400893423204992 , gaia2 , 374400893423204992 , Kiman2021 , 600573015 , 374400893423204992
4670526284404823808 , gaia2 , 4670526284404823808 , Kiman2021 , 31780319 , 4670526284404823808
4670526284404823808 , gaia2 , 4670526284404823808 , Kiman2021 , 650381163 , 4670526284404823808
4738546128148599296 , gaia2 , 4738546128148599296 , Kiman2021 , 201897406 , 4738546128148599296
4738546128148599296 , gaia2 , 4738546128148599296 , Kiman2021 , 650767423 , 4738546128148599296
5343603288120259072 , gaia2 , 5343603288120259072 , Kiman2021 , 375838965 , 5343603288120259072
5343603288120259072 , gaia2 , 5343603288120259072 , Kiman2021 , 931109420 , 5343603288120259072
5855801434094995584 , gaia2 , 5855801434094995584 , Kiman2021 , 329161967 , 5855801434094995584
5855801434094995584 , gaia2 , 5855801434094995584 , Kiman2021 , 959134031 , 5855801434094995584
6244148803549549312 , gaia2 , 6244148803549549312 , Kiman2021 , 48963011 , 6244148803549549312
6244148803549549312 , gaia2 , 6244148803549549312 , Kiman2021 , 1259769920 , 6244148803549549312
6388245295629220608 , gaia2 , 6388245295629220608 , Kiman2021 , 2054867096 , 6388245295629220608
6388245295629220608 , gaia2 , 6388245295629220608 , Kiman2021 , 260889990 , 6388245295629220608
661211147230556160 , gaia2 , 661211147230556160 , Kiman2021 , 800895150 , 661211147230556160
661211147230556160 , gaia2 , 661211147230556160 , Kiman2021 , 175261870 , 661211147230556160
J16553529-0823401 , 2MASS , J16553529-0823401 , Pass2024 , 471012515 , --
J16553529-0823401 , 2MASS , J16553529-0823401 , Pass2024 , 181609153 , 4339417394313320192

In [99]:
targets.to_csv(data_folder + 'extra_target_TICS.csv', index=False)

In [100]:
targets

,object,source_survey_name,source_survey_id,ref,TIC_ID,Gaia_ID,msg
0,109628013733250304,gaia2,109628013733250304,Kiman2021,371422484,109628013733250304,1 result
1,128095411034209536,gaia2,128095411034209536,Kiman2021,22749484,128095411034209536,1 result
2,1321738561431758592,gaia2,1321738561431758592,Kiman2021,188575751,1321738561431758592,1 result
3,132363027978672000,gaia2,132363027978672000,Kiman2021,285466899,132363027978672000,1 result
4,132592688469662208,gaia2,132592688469662208,Kiman2021,285277970,132592688469662208,1 result
...,...,...,...,...,...,...,...
1206,UCAC4 669-046011,UCAC4,669-046011,LWRD,189942913,962092607249662592,1 result
1207,UCAC4 678-130516,UCAC4,678-130516,LWRD,173462284,1941126622803033984,1 result
1208,UCAC4 681-049380,UCAC4,681-049380,LWRD,22635808,928827570144344448,1 result
1209,UCAC4 692-060564,UCAC4,692-060564,LWRD,47937289,2119839387352940288,1 result
1210,UCAC4 729-006249,UCAC4,729-006249,LWRD,453011250,418582156851693824,1 result

## Get TMags from TICs

In [14]:
tic = moca_old['target_name'][0]
# tic = '9964140'

In [15]:
tic

'4374147'

In [16]:
res = Catalogs.query_criteria(catalog='Tic',ID=tic)

In [17]:
res['Tmag']

<MaskedColumn name='Tmag' dtype='float64' length=1>
9.16291

In [ ]:

for i,r in moca_old.iterrows():
    if i % 500 == 0:
        print(f'Processing target {i+1}/{len(moca_old)}')
    res = Catalogs.query_criteria(catalog='Tic',ID=r.target_name)
    moca_old.loc[i,'Tmag'] = res[0]['Tmag']

Processing target 1/150

In [10]:
hosts

            hostname      TIC_ID           GaiaDR3_ID      Tmag
0             11 Com    72437047  3946945413106333696   3.83790
1             11 UMi   230061010  1696798367260229376   3.82294
2             14 And   333225860  1920113512486282240   4.32140
3             14 Her   219483057  1385293808145621504   5.86310
4           16 Cyg B    27533327  2135550755683407232   5.62810
...              ...         ...                  ...       ...
4229            XO-6   138168780  1114308481603347584   9.88278
4230            XO-7   268403451  2303332931542914048  10.05210
4231          YZ Cet   439403362  2358524597030794112   9.07000
4232  ZTF J1230-2655   951438622  3475360576690175616  18.80860
4233  ZTF J1828+2308  1685332572  4529477698683435264  18.13360

[4234 rows x 4 columns]

In [11]:
hosts.to_csv(hosts_folder + 'host_ids_with_Tmags.csv', index=False)

### Data Load

In [23]:
m_m_2022 = data_folder + 'apjac7da8t2_ascii.txt'
M_WD_2022 = data_folder + 'apjac7da8t3_ascii.txt'
readme_2023 = data_folder + '2023_ReadMe.txt'
t1_2023 = data_folder + '2023_table1.dat'

M_M_formatted = data_folder + 'Pass2022_MM_binaries.csv'
M_WD_formatted = data_folder + 'Pass2022_M_WD_binaries.csv'
t1_formatted = data_folder + 'Pass2023_table1.csv'

In [28]:
f = data_folder + '2024_apjad3631t3_mrt.txt'
t = Table.read(f, format="ascii.cds")

In [30]:
df = t.to_pandas()

In [31]:
df.to_csv(data_folder + 'Pass2024_MM_systems.csv', index=False)

In [13]:
meta_headers = pd.read_csv(readme_2023,
                               skiprows=92,
                               nrows=1,
                               header=None,
                               delim_whitespace=True
                         ).values[0]

/var/folders/lf/sq3cxxf17kv47p5lcv6w5t5r0000gn/T/ipykernel_50749/3788376468.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  meta_headers = pd.read_csv(readme_2023,

In [14]:
meta_headers

array(['Bytes', 'Format', 'Units', 'Label', 'Explanations'], dtype=object)

In [19]:
meta_data = pd.read_fwf(readme_2023,
                               widths=[9,6,7,12,100],
                               header=88,
                                nrows=19,
                               names=meta_headers
                         )

In [20]:
meta_data = meta_data.dropna(subset=['Bytes'])

In [21]:
meta_data

,Bytes,Format,Units,Label,Explanations
0,1- 13,A13,---,Name,Star name
1,15- 37,A23,---,2MASS,2MASS identifier
2,39- 39,A1,---,Inst,"Instrument, T:TRES; C:CHIRON"
3,41- 42,I2,---,Nobs,[2/21] Number of spectroscopic observations
4,44- 48,F5.3,Msun,Mass,"[0.1/0.29] Stellar mass, solar units"
5,50- 54,F5.3,Rsun,Rad,"[0.15/0.3] Stellar radius, solar units"
6,56- 61,F6.2,0.1nm,EWHa,[-17.2/-1.02] Median equivalent width of
8,63- 66,F4.1,km/s,vsini,"[0/56.3] Median vsini, projected rotational"
10,68- 71,F4.1,km/s,e_vsini,[0/11] vsini standard deviation
11,73- 76,F4.2,---,sini,[0.29/1.0]? sin(inclination)
12,78- 82,F5.3,km/s,MedeRVel,[0.02/2.14] Median epoch RV uncertainty
13,84- 89,F6.2,---,logPChi2,[-27.2/-0.01] log(P({chi}^2^)) of a constant
15,91- 96,F6.3,d,Per,[0.11/93.8]? Rotation period
16,98-102,F5.3,mag,Amp,[0.002/0.05]? Amplitude (peak-to-peak) of
18,104-105,I2,---,Ref,[1/10]? Rotation reference (3)

In [22]:
data_widths = []

for k in range(len(meta_data['Bytes'].values)):
    c = meta_data['Bytes'].values[k]
    try:
        i = c.index('-')
        start = int(c[0:i])
        end = int(c[i+1:])
        data_widths.append(end - start + 2)
    except:
        data_widths.append(2)

In [24]:
data = pd.read_fwf(t1_2023,
                               widths=data_widths,
                               header=None,
                               names=meta_data['Label'].values
                         )

In [25]:
data

,Name,2MASS,Inst,Nobs,Mass,Rad,EWHa,vsini,e_vsini,sini,MedeRVel,logPChi2,Per,Amp,Ref
0,2MA0505-4756,2MASS J05051443-4756154,C,4,0.159,0.195,-2.37,13.9,0.3,1.00,0.317,-0.04,0.726,0.004,3.0
1,2MA2009-0113,2MASS J20091824-0113377,T,4,0.146,0.186,-6.15,4.5,0.5,0.66,0.047,-0.95,1.374,0.017,2.0
2,APCOL,2MASS J06045215-3433360,C,4,0.279,0.285,-8.26,15.7,0.4,1.00,0.131,-0.46,1.013,0.009,3.0
3,APM0237-5928,2MASS J02363244-5928057,C,4,0.147,0.187,-5.69,20.5,0.3,1.00,0.213,-1.76,0.469,0.025,2.0
4,G141-36,2MASS J18481752+0741210,T,12,0.136,0.179,-3.89,3.2,0.4,NaN,0.027,-0.29,2.756,0.005,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,WIS1540-5101,2MASS J15404341-5101357,C,4,0.105,0.158,-1.21,0.6,0.3,NaN,0.020,-0.87,93.702,0.006,2.0
119,WIS1824-0536,2MASS J18242359-0536488,T,2,0.115,0.165,-7.38,3.4,2.1,0.57,0.126,-1.46,1.422,0.007,9.0
120,WT2458,2MASS J09455843-3253299,C,4,0.186,0.214,-5.20,20.5,0.6,0.59,0.222,-0.20,0.312,0.009,3.0
121,WT84,2MASS J02172845-5922435,C,4,0.126,0.172,-10.48,4.1,0.5,NaN,0.086,-0.28,5.232,0.018,2.0
122,WT887,2MASS J22135048-6342100,C,4,0.108,0.160,-3.00,26.2,10.4,0.46,2.140,-0.15,0.143,0.008,4.0

In [26]:
data.to_csv(t1_formatted, index=False)

In [40]:
ra_hours = data['RAh'].values  # RA hours
ra_minutes = data['RAm'].values  # RA minutes
ra_seconds = data['RAs'].values  # RA seconds

dec_degrees = data['DEd'].values  # Dec degrees
dec_minutes = data['DEm'].values  # Dec minutes
dec_seconds = data['DEs'].values  # Dec seconds

# Create SkyCoord object
coord = SkyCoord(ra=ra_hours*u.hour + ra_minutes*u.minute + ra_seconds*u.second,
                 dec=dec_degrees*u.deg + dec_minutes*u.arcmin + dec_seconds*u.arcsec, 
                 frame='icrs')

# Convert RA and Dec to degrees
ra_in_degrees = coord.ra.deg
dec_in_degrees = coord.dec.deg

data['RA_deg'] = ra_in_degrees
data['DE_deg'] = dec_in_degrees

In [38]:
data.to_csv(datafile_formatted)