In [1]:
import pandas as pd
from astropy.coordinates import SkyCoord
import astropy.units as u
from astropy.table import Table

## Data loads

### Folder parsing

In [77]:
data_folder = '/Users/philvanlane/Documents/lc_ae/data/'

### Data Load

In [78]:
readme = data_folder + 'TIME_table.mrt'
data = data_folder + 'TIME_table.mrt'
data_formatted = data_folder + 'TIME_table.csv'

In [79]:
meta_headers = pd.read_csv(readme,
                               skiprows=6,
                               nrows=1,
                               header=None,
                               delim_whitespace=True
                         ).values[0]

/var/folders/lf/sq3cxxf17kv47p5lcv6w5t5r0000gn/T/ipykernel_21128/618759517.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  meta_headers = pd.read_csv(readme,

In [80]:
meta_headers

array(['Bytes', 'Format', 'Units', 'Label', 'Explanations'], dtype=object)

In [83]:
meta_data = pd.read_fwf(readme,
                               widths=[9,6,7,9,100],
                               header=5,
                                nrows=17,
                               names=meta_headers
                         )

In [71]:
meta_data = meta_data.dropna(subset=['Bytes'])

In [84]:
meta_data

,Bytes,Format,Units,Label,Explanations
0,1- 15,A16,---,Name,Host star name
1,17,A2,---,Binary,Binary flag
2,19- 22,F5.0,K,Teff,Effective temperature
3,24- 29,F5.2,dex,[Fe/H],Metallicity
4,31- 36,F6.2,d,Prot,Rotation period
5,38- 42,F5.2,d,e_Prot,Rotatio period uncertainty
6,44- 45,A2,---,Method,Method for obtaining rotation period (1)
7,47- 51,F5.2,Gyr,Age,Estimated age
8,53- 56,F5.2,Gyr,e_Age,Age uncertainty
9,58- 62,F5.2,Gyr,corr,Metallicity-dependent age correction
10,64,A1,---,fail,Flag for age assignment failure
11,66,A1,---,ul,Flag for upper limit
12,68,A1,---,pms,Flag for pre-main sequence star
13,70,A1,---,no_err,Flag for lack of a reported period error (2)
14,72-105,A37,---,Note,Instrument key and citation for rotation perio...

In [98]:
data_widths = []

for k in range(len(meta_data['Bytes'].values)):
    c = meta_data['Bytes'].values[k]
    try:
        i = c.index('-')
        start = int(c[0:i])
        end = int(c[i+1:])
        data_widths.append(end - start + 2)
    except:
        data_widths.append(2)

In [99]:
data_widths[3]=5

In [100]:
data_widths[8]=6

In [101]:
df = pd.read_fwf(data,
                               widths=data_widths,
                               header=28,
                               names=meta_data['Label'].values
                         )

In [102]:
df

,Name,Binary,Teff,[Fe/H],Prot,e_Prot,Method,Age,e_Age,corr,fail,ul,pms,no_err,Note
0,EPIC 201170410,Y,3650,-0.05,20.16,1.60,P,1.78,0.58,0.03,N,N,N,N,K2 this work
1,EPIC 211822797,-,3856,0.14,15.88,0.72,P,1.18,0.24,0.03,N,N,N,N,K2 Reinhold2020
2,G 264-012,-,3326,0.10,100.00,6.00,PS,6.70,3.28,NaN,N,N,N,N,TE/ME/AN/CA Amado2021
3,G 9-40,-,3713,0.04,34.08,11.46,P,5.35,2.56,0.07,N,N,N,N,K2 Reinhold2020
4,GJ 1132,-,3270,-0.12,122.30,5.50,P,6.25,3.18,NaN,N,N,N,N,ME Cloutier2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,KOI-5162,Y,3697,-0.30,17.35,1.24,P,2.46,0.57,NaN,N,N,N,N,Ke Santos2019
246,KOI-2453,Y,3462,-0.42,59.17,5.71,P,5.72,1.00,-1.76,N,N,N,N,Ke Santos2019
247,KOI-463,Y,3395,-0.12,50.81,3.65,P,3.09,0.37,-0.02,N,N,N,N,Ke Santos2019
248,KOI-249,Y,3547,-0.14,46.43,3.32,P,5.58,0.80,-0.36,N,N,N,N,Ke Santos2019
249,KOI-1940,Y,3738,0.00,18.34,1.39,P,NaN,NaN,NaN,Y,N,N,N,Ke Santos2019

In [103]:
df.to_csv(data_formatted, index=False)

In [40]:
ra_hours = data['RAh'].values  # RA hours
ra_minutes = data['RAm'].values  # RA minutes
ra_seconds = data['RAs'].values  # RA seconds

dec_degrees = data['DEd'].values  # Dec degrees
dec_minutes = data['DEm'].values  # Dec minutes
dec_seconds = data['DEs'].values  # Dec seconds

# Create SkyCoord object
coord = SkyCoord(ra=ra_hours*u.hour + ra_minutes*u.minute + ra_seconds*u.second,
                 dec=dec_degrees*u.deg + dec_minutes*u.arcmin + dec_seconds*u.arcsec, 
                 frame='icrs')

# Convert RA and Dec to degrees
ra_in_degrees = coord.ra.deg
dec_in_degrees = coord.dec.deg

data['RA_deg'] = ra_in_degrees
data['DE_deg'] = dec_in_degrees

In [38]:
data.to_csv(datafile_formatted)