In [1]:
from astroquery.vizier import Vizier
import pandas as pd
import numpy as np

Vizier.ROW_LIMIT = -1

In [2]:
data_folder = '/Users/philvanlane/Documents/lc_ae/data/'
stars = pd.read_csv(data_folder + 'thickdisk_dr3.csv')
gids = stars['dr3_source_id'].tolist()

In [6]:
all_stars['MG_quick'] = all_stars['G0'] + 5 * np.log10(all_stars['parallax']) - 10

In [8]:
all_stars.to_csv(data_folder + 'phot_all.csv', index=False)

In [3]:
result = Vizier.query_constraints(
        catalog="I/352/gedr3dis",
        Source=gids[0])

In [4]:
df = pd.DataFrame(columns=result['I/352/gedr3dis'].colnames)

In [5]:
df

Empty DataFrame
Columns: [Source, RA_ICRS, DE_ICRS, rgeo, b_rgeo, B_rgeo, rpgeo, b_rpgeo, B_rpgeo, Flag]
Index: []

In [7]:
df

,Source,RA_ICRS,DE_ICRS,rgeo,b_rgeo,B_rgeo,rpgeo,b_rpgeo,B_rpgeo,Flag
0,3803707463510348928,165.313043,-0.715112,333.191711,330.677063,335.664337,333.894226,331.168915,337.132874,10033
1,2382320781730066048,351.66687,-22.723736,107.347633,107.17981,107.523399,107.334946,107.159668,107.503082,10033
2,5040596850064598400,20.850135,-24.026115,660.115356,651.495605,670.24292,658.622314,648.958801,667.749207,10033
3,5419534972706899072,149.215837,-41.347317,200.423492,199.820374,200.881241,201.005539,200.178467,201.491791,10033
4,2343051792663454976,9.988743,-28.035375,203.731018,203.1091,204.340561,203.574799,202.887482,204.306412,10033
...,...,...,...,...,...,...,...,...,...,...
5215,6290518782302606464,209.702129,-19.853511,913.598938,889.026733,941.623962,920.955688,893.229736,948.342834,10033
5216,1612014170944761472,215.473137,58.416488,157.022736,156.72728,157.379028,157.056137,156.775406,157.336456,10033
5217,2626650579162197248,336.388931,-4.026338,225.620224,224.848816,226.390717,225.710068,224.761215,226.597229,10033
5218,3553706178943999360,159.378738,-20.716167,627.117859,612.052429,639.984436,628.487854,615.874756,644.563477,10033
5219,4010333804635798144,185.381741,28.905042,54.784252,54.642281,54.923882,54.840061,54.706509,54.958778,10033

In [8]:

for i in range(len(gids)):
    if i % 500 == 0:
        print(f"Processing {i} of {len(gids)}")
    if len(df.loc[df['Source'] == gids[i]]) > 0:
        continue
    result = Vizier.query_constraints(
        catalog="I/352/gedr3dis",
        Source=gids[i]
    )
    if result.keys() == []:
        print(f"No result for {gids[i]}")
        continue
    df_record = result['I/352/gedr3dis'].to_pandas()
    df = pd.concat([df, df_record], ignore_index=True)

Processing 0 of 6084
Processing 500 of 6084
Processing 1000 of 6084
Processing 1500 of 6084
Processing 2000 of 6084
Processing 2500 of 6084
Processing 3000 of 6084
Processing 3500 of 6084
Processing 4000 of 6084
Processing 4500 of 6084
Processing 5000 of 6084
Processing 5500 of 6084
Processing 6000 of 6084

In [9]:
df

,Source,RA_ICRS,DE_ICRS,rgeo,b_rgeo,B_rgeo,rpgeo,b_rpgeo,B_rpgeo,Flag
0,3803707463510348928,165.313043,-0.715112,333.191711,330.677063,335.664337,333.894226,331.168915,337.132874,10033
1,2382320781730066048,351.66687,-22.723736,107.347633,107.17981,107.523399,107.334946,107.159668,107.503082,10033
2,5040596850064598400,20.850135,-24.026115,660.115356,651.495605,670.24292,658.622314,648.958801,667.749207,10033
3,5419534972706899072,149.215837,-41.347317,200.423492,199.820374,200.881241,201.005539,200.178467,201.491791,10033
4,2343051792663454976,9.988743,-28.035375,203.731018,203.1091,204.340561,203.574799,202.887482,204.306412,10033
...,...,...,...,...,...,...,...,...,...,...
6056,5097938546117783552,61.783725,-15.612908,1035.36023,1007.29321,1078.24829,1070.16614,1035.01428,1103.24731,10033
6057,6532473531539358208,359.976547,-44.870897,691.88562,678.328247,705.788269,690.987549,677.787659,704.967651,10033
6058,2504432611830170368,28.310434,-3.403352,690.325684,674.662354,709.75238,689.244202,675.911743,706.40918,10033
6059,1688865463880916096,192.62725,69.835361,829.221985,791.32782,877.999695,884.848145,831.33252,921.971985,10033
6060,3892975987936521216,181.023445,3.338195,71.155861,71.004196,71.28231,71.163925,71.048355,71.3041,10033

In [10]:
df.to_csv(data_folder + 'thickdisk_bj_distances.csv', index=False)

In [15]:
df = pd.DataFrame(columns=result['I/352/gedr3dis'].colnames)

In [22]:
df

Empty DataFrame
Columns: [Source, RA_ICRS, DE_ICRS, rgeo, b_rgeo, B_rgeo, rpgeo, b_rpgeo, B_rpgeo, Flag]
Index: []

In [17]:

df_record = result['I/352/gedr3dis'].to_pandas()
df = pd.concat([df, df_record], ignore_index=True)

/var/folders/lf/sq3cxxf17kv47p5lcv6w5t5r0000gn/T/ipykernel_37755/2249595755.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_record], ignore_index=True)