In [20]:
from astroquery.vizier import Vizier
import pandas as pd
import numpy as np

Vizier.ROW_LIMIT = -1

In [22]:
data_folder = '/Users/philvanlane/Documents/lc_ae/data/'
stars = pd.read_csv(data_folder + 'mocadb_add_TICS.csv')
gids = stars['GaiaDR3_ID'].tolist()

In [6]:
all_stars['MG_quick'] = all_stars['G0'] + 5 * np.log10(all_stars['parallax']) - 10

In [8]:
all_stars.to_csv(data_folder + 'phot_all.csv', index=False)

In [24]:
result = Vizier.query_constraints(
        catalog="I/352/gedr3dis",
        Source=gids[0])

In [25]:
df = pd.DataFrame(columns=result['I/352/gedr3dis'].colnames)

In [32]:
df

,Source,RA_ICRS,DE_ICRS,rgeo,b_rgeo,B_rgeo,rpgeo,b_rpgeo,B_rpgeo,Flag
0,414514646721724032,13.026779,49.623362,733.986633,709.490051,756.199829,725.094055,704.474182,755.007141,10033
1,414508878584171904,13.132744,49.451849,690.244324,683.809082,696.913208,690.156860,684.473267,695.845642,10033
2,3446881477482884352,79.974390,30.585992,2574.245360,2401.228030,2756.502200,2709.210210,2490.057860,2925.365720,10033
3,3446833614367652992,80.121089,30.544855,3062.725100,2673.389160,3581.124270,3173.512210,2648.868160,3933.863040,10033
4,3157241252544842496,104.427380,8.276972,5556.478030,3929.760740,7679.538570,5122.821780,4283.827640,6378.728520,10033
...,...,...,...,...,...,...,...,...,...,...
2082,5376938556516479104,170.850885,-43.327003,1050.021970,1039.444820,1065.394530,1049.944210,1037.535030,1060.762820,10033
2083,5382185318628228352,171.411062,-43.232994,978.182922,959.373291,1000.692930,974.297302,957.895020,997.287781,10033
2084,5382185700881633408,171.359259,-43.189991,1005.500980,982.050964,1023.246830,1018.497800,1003.099490,1034.112790,10033
2085,5382182230549912448,171.651759,-43.253862,993.195251,979.541870,1009.321410,991.449097,974.512573,1006.212400,10033
2086,5835869899695725184,238.970440,-57.407897,2461.133790,2309.961670,2609.932370,2420.613280,2277.324950,2609.452640,10033

In [34]:

for i in range(len(gids)):
    if i % 500 == 0:
        print(f"Processing {i} of {len(gids)}")
    if len(df.loc[df['Source'] == gids[i]]) > 0:
        continue
    result = Vizier.query_constraints(
        catalog="I/352/gedr3dis",
        Source=gids[i]
    )
    if result.keys() == []:
        print(f"No result for {gids[i]}")
        continue
    df_record = result['I/352/gedr3dis'].to_pandas()
    df = pd.concat([df, df_record], ignore_index=True)

Processing 0 of 3427
Processing 500 of 3427
Processing 1000 of 3427
Processing 1500 of 3427
Processing 2000 of 3427
No result for 342868824084286848
No result for 342916446681649792
No result for 344142058551615488
Processing 2500 of 3427
Processing 3000 of 3427

In [35]:
df

,Source,RA_ICRS,DE_ICRS,rgeo,b_rgeo,B_rgeo,rpgeo,b_rpgeo,B_rpgeo,Flag
0,414514646721724032,13.026779,49.623362,733.986633,709.490051,756.199829,725.094055,704.474182,755.007141,10033
1,414508878584171904,13.132744,49.451849,690.244324,683.809082,696.913208,690.156860,684.473267,695.845642,10033
2,3446881477482884352,79.974390,30.585992,2574.245360,2401.228030,2756.502200,2709.210210,2490.057860,2925.365720,10033
3,3446833614367652992,80.121089,30.544855,3062.725100,2673.389160,3581.124270,3173.512210,2648.868160,3933.863040,10033
4,3157241252544842496,104.427380,8.276972,5556.478030,3929.760740,7679.538570,5122.821780,4283.827640,6378.728520,10033
...,...,...,...,...,...,...,...,...,...,...
3418,4161178691096753792,274.930729,-5.537850,928.310364,910.912170,943.971008,922.205444,907.380249,939.557373,10033
3419,1814376090584994048,310.455420,20.442814,922.558167,911.866211,935.556702,922.614563,911.049011,935.980286,10033
3420,1817350888013852416,310.027929,20.310938,939.662842,927.797668,953.136169,939.303040,930.208435,951.570190,10033
3421,1814348770293332224,310.381208,20.250975,946.142395,914.385071,981.615967,938.878052,908.242859,969.082458,10033
3422,1817346867924415360,310.094746,20.271570,895.975830,885.560730,908.707825,896.674255,886.410767,906.892395,10033

In [36]:
df.to_csv(data_folder + 'moca_add_bj_distances.csv', index=False)

In [15]:
df = pd.DataFrame(columns=result['I/352/gedr3dis'].colnames)

In [22]:
df

Empty DataFrame
Columns: [Source, RA_ICRS, DE_ICRS, rgeo, b_rgeo, B_rgeo, rpgeo, b_rpgeo, B_rpgeo, Flag]
Index: []

In [17]:

df_record = result['I/352/gedr3dis'].to_pandas()
df = pd.concat([df, df_record], ignore_index=True)

/var/folders/lf/sq3cxxf17kv47p5lcv6w5t5r0000gn/T/ipykernel_37755/2249595755.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_record], ignore_index=True)