In [8]:
from astroquery.vizier import Vizier
import pandas as pd

Vizier.ROW_LIMIT = -1

In [19]:
hosts_folder = '/Users/philvanlane/Documents/lc_ae/exop_hosts/'
hosts = pd.read_csv(hosts_folder + 'host_ids.csv')
gids = hosts['GaiaDR3_ID'].tolist()

In [21]:
df = pd.DataFrame(columns=result['I/352/gedr3dis'].colnames)

In [24]:
df

,Source,RA_ICRS,DE_ICRS,rgeo,b_rgeo,B_rgeo,rpgeo,b_rpgeo,B_rpgeo,Flag
0,3946945413106333696,185.178763,17.793264,97.975876,96.675736,99.105682,97.955444,96.889702,99.236366,10033
1,1696798367260229376,229.274597,71.823944,126.057068,124.708969,127.323578,126.092903,124.826370,127.703278,10033
2,1920113512486282240,352.824201,39.235825,75.847183,75.409172,76.266884,75.791130,75.302040,76.270180,10033
3,1385293808145621504,242.602127,43.816321,17.892342,17.884134,17.902576,17.891458,17.882992,17.899111,10033
4,2135550755683407232,295.465613,50.516802,21.118748,21.110294,21.126801,21.115828,21.108782,21.122457,10033
...,...,...,...,...,...,...,...,...,...,...
630,4201307051566729984,289.999852,-9.325014,48.140148,48.083527,48.194374,48.142849,48.076004,48.208855,10033
631,6770761168986617600,290.267401,-23.619704,120.074760,119.788017,120.369247,119.925659,119.649208,120.191063,10033
632,116037204451525376,43.914066,26.872356,22.486519,22.476746,22.498615,22.488110,22.477812,22.498808,10033
633,6434153380720177664,291.287293,-66.467751,26.976078,26.962091,26.990803,26.973360,26.958780,26.988052,10033
634,6745589980571162752,290.721237,-32.920898,59.834866,59.738667,59.923195,59.842754,59.753140,59.936962,10033

In [27]:

for i in range(len(gids)):
    if i % 500 == 0:
        print(f"Processing {i} of {len(gids)}")
    if len(df.loc[df['Source'] == gids[i]]) > 0:
        continue
    result = Vizier.query_constraints(
        catalog="I/352/gedr3dis",
        Source=gids[i]
    )
    if result.keys() == []:
        print(f"No result for {gids[i]}")
        continue
    df_record = result['I/352/gedr3dis'].to_pandas()
    df = pd.concat([df, df_record], ignore_index=True)

Processing 0 of 4234
Processing 500 of 4234
No result for 4224259562941398400
Processing 1000 of 4234
No result for 3393982701757444352
No result for 2051807620790721792
Processing 1500 of 4234
No result for 2075063150726110208
No result for 2073299327911286144
No result for 2100643632324807296
No result for 2102161989163432832
Processing 2000 of 4234
No result for 2076834463947219584
No result for 2101508501301083520
Processing 2500 of 4234
Processing 3000 of 4234
No result for 2073776859551124992
No result for 2078696005850500608
No result for 6049072007438134272
Processing 3500 of 4234
Processing 4000 of 4234

In [29]:
df.to_csv(hosts_folder + 'bj_distances.csv', index=False)

In [15]:
df = pd.DataFrame(columns=result['I/352/gedr3dis'].colnames)

In [22]:
df

Empty DataFrame
Columns: [Source, RA_ICRS, DE_ICRS, rgeo, b_rgeo, B_rgeo, rpgeo, b_rpgeo, B_rpgeo, Flag]
Index: []

In [17]:

df_record = result['I/352/gedr3dis'].to_pandas()
df = pd.concat([df, df_record], ignore_index=True)

/var/folders/lf/sq3cxxf17kv47p5lcv6w5t5r0000gn/T/ipykernel_37755/2249595755.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_record], ignore_index=True)